# Generated by Django 3.0.4 on 2020-11-13 15:47

from django.db import migrations, models
import django.db.models.deletion
import product_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=264, verbose_name='Book Name')),
                ('book_author', models.CharField(blank=True, max_length=100, verbose_name='Author Name')),
                ('book_price', models.PositiveIntegerField(verbose_name='Display Price')),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=False, verbose_name='Is Book in Stock?')),
                ('book_category', models.ManyToManyField(to='product_app.BookCategory', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product_app.models.get_image_file_name)),
                ('is_default', models.BooleanField(default=True, help_text='By checking this the photo will appear on product template else not')),
                ('image_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Book', verbose_name='Image Belongs to?')),
            ],
        ),
    ]
