# Generated by Django 3.0.4 on 2020-11-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_remove_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Author', verbose_name='Author Name'),
            preserve_default=False,
        ),
    ]
