# Generated by Django 3.0.4 on 2020-12-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0005_book_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_first_name', models.CharField(max_length=100)),
                ('billing_last_name', models.CharField(max_length=100)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.CharField(max_length=364)),
                ('billing_phone_number', models.CharField(max_length=20)),
                ('shipping_first_name', models.CharField(max_length=100)),
                ('shipping_last_name', models.CharField(max_length=100)),
                ('shipping_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_address', models.CharField(max_length=364)),
                ('shipping_phone_number', models.CharField(max_length=20)),
                ('order_status', models.IntegerField(choices=[(1, 'Not confirmed'), (2, 'Confirmed'), (3, 'Delivered')], default=1)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid')], default=1)),
                ('order_guideline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortBookInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=264, verbose_name='Book Name')),
                ('book_price', models.PositiveIntegerField(verbose_name='Display Price')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_orders.Order')),
                ('short_book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_orders.ShortBookInformation')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='book_orders.OrderItem', to='product_app.Book'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
