# Generated by Django 3.0.4 on 2020-12-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='short_book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_orders.ShortBookInformation'),
        ),
    ]
