# Generated by Django 3.0.4 on 2020-12-20 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_orders', '0003_auto_20201220_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
