# Generated by Django 3.0.4 on 2020-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_orders', '0004_order_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_guideline',
            field=models.TextField(blank=True),
        ),
    ]
